all: CodeLine.class Operation.class PassOne.class SymbolTable.class
CodeLine.class: passOne/CodeLine.java
	javac passOne/CodeLine.java
Operation.class: passOne/Operation.java
	javac passOne/Operation.java
PassOne.class: passOne/PassOne.java
	javac passOne/PassOne.java
SymbolTable.class: passOne/SymbolTable.java
	javac passOne/SymbolTable.java